In [3]:
import numpy as np
import onnxruntime as ort

In [14]:
model = ort.InferenceSession('/Users/jacksonfraser/Desktop/ubc/capstone/rl-unicycle/src/rluni/configs/rlmodels/broomy-rnn-feb12th.onnx')

In [15]:
print([m.name for m in model.get_inputs()])

['obs', 'out_state.1', 'hidden_state.1']


In [16]:
print([m.name for m in model.get_outputs()])

['mu', 'log_std', 'value', 'out_state', 'hidden_state']


In [17]:
obs = np.zeros((1, 9))
actions = model.run(None, {"obs": obs.astype(np.float32), "out_state.1": np.zeros((1, 1, 128)).astype(np.float32), "hidden_state.1": np.zeros((1, 1, 128)).astype(np.float32)})


In [18]:
actions

[array([[0.05504799, 0.2778468 ]], dtype=float32),
 array([[-3.1699083, -2.074505 ]], dtype=float32),
 array([[1.5618992]], dtype=float32),
 array([[[ 9.04432591e-03, -6.79589948e-03,  1.25427488e-02,
          -2.32757311e-02, -1.57420486e-02,  8.45721271e-03,
           2.32127029e-02, -7.65375653e-03, -2.60944646e-02,
          -7.83152971e-03,  1.17364237e-02,  2.97914501e-02,
           4.46382575e-02, -7.82638323e-03, -3.70530295e-03,
           1.40966289e-02, -2.25135195e-03,  9.19411145e-03,
          -1.49033805e-02,  1.99840078e-03, -8.93144961e-03,
           2.79671811e-02,  2.81466879e-02,  9.97156836e-04,
          -3.19060497e-02, -2.99081337e-02,  2.30144542e-02,
          -1.22340089e-02,  2.60337181e-02, -8.30501132e-03,
           2.40512248e-02, -5.17580716e-04,  1.85872465e-02,
           1.63732357e-02, -4.01567221e-02,  1.90907326e-02,
           6.22361913e-05,  2.50991210e-02,  1.42484652e-02,
           3.22140455e-02, -3.80276032e-02,  2.79211160e-02,
      

In [7]:
actions[0][0]

array([-0.02400041, -0.09359825, -1.1114429 ], dtype=float32)

In [16]:
actions[-1].shape

(1, 1, 64)