In [2]:
import numpy as np
import onnxruntime as ort

In [3]:
model = ort.InferenceSession('/Users/jacksonfraser/Desktop/ubc/capstone/rl-unicycle/src/rluni/configs/rlmodels/broomy-balance-export.onnx')

In [4]:
print([m.name for m in model.get_inputs()])

['obs', 'out_state.1', 'hidden_state.1']


In [5]:
print([m.name for m in model.get_outputs()])

['mu', 'log_std', 'value', 'out_state', 'hidden_state']


In [11]:
obs = np.zeros((1, 9))
actions = model.run(None, {"obs": obs.astype(np.float32), "out_state.1": np.zeros((1, 1, 64)).astype(np.float32), "hidden_state.1": np.zeros((1, 1, 64)).astype(np.float32)})


In [14]:
actions

[array([[-0.19074686, -0.5709284 , -0.39757788]], dtype=float32),
 array([[-1.7873815 , -1.550586  , -0.73877263]], dtype=float32),
 array([[-0.9873324]], dtype=float32),
 array([[[-0.00451732, -0.01676596, -0.0818724 ,  0.21182357,
           0.02333322,  0.0218096 ,  0.17683436,  0.07081157,
           0.0035315 ,  0.01028517, -0.01981945, -0.1112252 ,
           0.02941623, -0.00606415, -0.00851626, -0.02299573,
          -0.22148655, -0.02170232,  0.19524302,  0.0739871 ,
          -0.23152182, -0.07571425,  0.02302839,  0.34457266,
           0.04238996,  0.01519346,  0.15243208,  0.08324268,
           0.07985847,  0.01712808, -0.36759904,  0.25792718,
           0.06624041, -0.04645577,  0.08020545,  0.02812337,
          -0.05587363, -0.03311963, -0.03424046, -0.13455725,
           0.05310815,  0.11388183, -0.00977035, -0.05423302,
          -0.02903421, -0.07381475,  0.02723096, -0.00874727,
          -0.00472804, -0.00219052, -0.00403425,  0.04976271,
           0.02202273, 

In [12]:
actions[0][0]

array([-0.19074686, -0.5709284 , -0.39757788], dtype=float32)

In [13]:
actions[-1].shape

(1, 1, 64)