In [1]:
import numpy as np
import onnxruntime as ort

In [2]:
model = ort.InferenceSession('/Users/jacksonfraser/Desktop/ubc/capstone/rl-unicycle/src/rluni/configs/rlmodels/broomy-rnn-feb12th.onnx')

In [3]:
print([m.name for m in model.get_inputs()])

['obs', 'out_state.1', 'hidden_state.1']


In [4]:
print([m.name for m in model.get_outputs()])

['mu', 'log_std', 'value', 'out_state', 'hidden_state']


In [5]:
obs = np.zeros((1, 9))
actions = model.run(None, {"obs": obs.astype(np.float32), "out_state.1": np.zeros((1, 1, 128)).astype(np.float32), "hidden_state.1": np.zeros((1, 1, 128)).astype(np.float32)})


In [27]:
outputs = actions[0][0]
sigmas = np.exp(actions[1][0])

In [28]:
np.random.normal(outputs[0], sigmas[0])

0.05796799604057926

In [29]:
np.random.normal(outputs[1], sigmas[1])

0.3570921443361969

In [21]:
actions[0]

array([[0.05504799, 0.2778468 ]], dtype=float32)

In [9]:
actions[1].shape

(1, 2)

In [12]:
actions[1][0]

array([-3.1699083, -2.074505 ], dtype=float32)

In [11]:
actions[0]

array([[0.05504799, 0.2778468 ]], dtype=float32)