In [1]:
import numpy as np
import onnxruntime as ort

In [2]:
model = ort.InferenceSession('/Users/jacksonfraser/Desktop/ubc/capstone/rl-unicycle/src/rluni/configs/rlmodels/broomy-rnn-jan31th_exp.onnx')

In [3]:
print([m.name for m in model.get_inputs()])

['obs', 'out_state.1', 'hidden_state.1']


In [4]:
print([m.name for m in model.get_outputs()])

['mu', 'log_std', 'value', 'out_state', 'hidden_state']


In [6]:
obs = np.zeros((1, 9))
actions = model.run(None, {"obs": obs.astype(np.float32), "out_state.1": np.zeros((1, 1, 128)).astype(np.float32), "hidden_state.1": np.zeros((1, 1, 128)).astype(np.float32)})


In [8]:
actions

[array([[-0.02400041, -0.09359825, -1.1114429 ]], dtype=float32),
 array([[-3.373207 , -2.4247813, -0.3129179]], dtype=float32),
 array([[1.4171126]], dtype=float32),
 array([[[ 0.00618033, -0.03549904, -0.01505861, -0.03911414,
          -0.01467561,  0.02334247,  0.04040827, -0.00254128,
          -0.02798222,  0.0221696 ,  0.01317729,  0.00965454,
           0.08166133, -0.0493689 , -0.00130405,  0.02172917,
          -0.06099316, -0.01028199, -0.04325093,  0.1078259 ,
          -0.05535219,  0.02236613,  0.03076384,  0.08487517,
          -0.04981146, -0.03733674,  0.02081208, -0.02508527,
           0.03130104, -0.01598437,  0.00985663,  0.00102204,
           0.02537835,  0.07715507, -0.06236236, -0.0061778 ,
          -0.00792664, -0.00506774,  0.08001157,  0.02073544,
          -0.05815288,  0.04135881, -0.09358439,  0.00926039,
           0.10174413, -0.02302079,  0.01225465, -0.06265303,
           0.08654892,  0.00069225,  0.04132736,  0.0174898 ,
           0.03890966, -0.0

In [7]:
actions[0][0]

array([-0.02400041, -0.09359825, -1.1114429 ], dtype=float32)

In [16]:
actions[-1].shape

(1, 1, 64)